import {
  Activity, BadgePercent, BarChart3, Bell, BookOpen, Box, Building2, Calculator, CreditCard,
  FileText, FolderOpen, Gift, Globe, HelpCircle, Home, ImagePlus, Inbox, KeyRound, Keyboard,
  LayoutTemplate, LifeBuoy, Mail, Megaphone, Menu, MessageSquare, Package, PackageX, Phone,
  Plus, Radio, Search, Settings as SettingsIcon, ShieldCheck, ShoppingBag, Signpost, Smartphone,
  Sparkles, Star, Store, Tags, Truck, Users, Webhook, Zap,
} from 'lucide-react';

export const ALL_ROLES = ['admin', 'Owner', 'Manager', 'Staff', 'Warehouse', 'Support'];

export const ROLE_ACCESS = {
  orders:     ['admin', 'Owner', 'Manager', 'Staff', 'Warehouse', 'Support'],
  products:   ['admin', 'Owner', 'Manager', 'Staff', 'Warehouse'],
  customers:  ['admin', 'Owner', 'Manager', 'Staff', 'Support'],
  marketing:  ['admin', 'Owner', 'Manager'],
  storefront: ['admin', 'Owner', 'Manager'],
  analytics:  ['admin', 'Owner', 'Manager', 'Staff'],
  settings:   ['admin', 'Owner'],
  inbox:      ['admin', 'Owner', 'Manager', 'Staff', 'Warehouse', 'Support'],
  channels:   ['admin', 'Owner', 'Manager'],
  apps:       ['admin', 'Owner'],
  workspace:  ['admin', 'Owner'],
  discounts:  ['admin', 'Owner', 'Manager'],
};

export const NAV_TOP = [
  { to: '/admin', label: 'Home', icon: Home, end: true },
];

export const WORKSPACE_ITEMS = [
  { to: '/admin/workspace/current', label: 'Current Store' },
  { to: '/admin/workspace/all', label: 'All Stores' },
  { to: '/admin/workspace/add', label: 'Add Store' },
  { to: '/admin/workspace/switch', label: 'Switch Workspace' },
  { to: '/admin/workspace/settings', label: 'Workspace Settings' },
];

export const SEARCH_SCOPES = [
  { to: '/admin/search/products', label: 'Search Products' },
  { to: '/admin/search/orders', label: 'Search Orders' },
  { to: '/admin/search/customers', label: 'Search Customers' },
  { to: '/admin/search/pages', label: 'Search Pages' },
  { to: '/admin/search/apps', label: 'Search Apps' },
  { to: '/admin/search/settings', label: 'Search Settings' },
];

export const NAV_GROUPS = [
  {
    key: 'inbox', label: 'Inbox', icon: Inbox,
    match: ['/admin/inbox'],
    children: [
      { to: '/admin/inbox', label: 'All Messages', icon: Inbox },
      { to: '/admin/inbox/unread', label: 'Unread', icon: Bell },
      { to: '/admin/inbox/customers', label: 'Customer Messages', icon: MessageSquare },
      { to: '/admin/inbox/orders', label: 'Order Alerts', icon: ShoppingBag },
      { to: '/admin/inbox/products', label: 'Product Alerts', icon: Package },
      { to: '/admin/inbox/system', label: 'System Notifications', icon: Bell },
    ],
  },
  {
    key: 'orders', label: 'Orders', icon: ShoppingBag,
    match: ['/admin/orders', '/admin/payments', '/admin/abandoned-carts', '/admin/verification-queue', '/admin/ops', '/admin/fulfillment', '/admin/returns'],
    children: [
      { to: '/admin/orders', label: 'All Orders', icon: ShoppingBag },
      { to: '/admin/orders/new', label: 'Draft Orders', icon: FileText },
      { to: '/admin/abandoned-carts', label: 'Abandoned Checkouts', icon: PackageX },
      { to: '/admin/verification-queue', label: 'Verification queue', icon: Phone },
      { to: '/admin/fulfillment', label: 'Fulfillment', icon: Box },
      { to: '/admin/ops/returns', label: 'Returns', icon: PackageX },
      { to: '/admin/ops', label: 'Commerce OS', icon: Package },
      { to: '/admin/payments', label: 'Payments', icon: CreditCard },
      { to: '/admin/desk/orders/payment-issues', label: 'Payment Issues', icon: CreditCard },
      { to: '/admin/desk/orders/documents', label: 'Order Documents', icon: FileText },
      { to: '/admin/desk/orders/notifications', label: 'Order Notifications', icon: Bell },
      { to: '/admin/desk/orders/settings', label: 'Order Settings', icon: SettingsIcon },
    ],
  },
  {
    key: 'products', label: 'Products', icon: Package,
    match: ['/admin/products', '/admin/categories', '/admin/collections', '/admin/reviews', '/admin/questions', '/admin/catalog'],
    children: [
      { to: '/admin/catalog', label: 'Catalog', icon: Package },
      { to: '/admin/products', label: 'Inventory', icon: Package },
      { to: '/admin/categories', label: 'Categories', icon: Tags },
      { to: '/admin/collections', label: 'Collections', icon: FolderOpen },
      { to: '/admin/reviews', label: 'Reviews', icon: Star },
      { to: '/admin/questions', label: 'Questions', icon: MessageSquare },
      { to: '/admin/desk/products/attributes', label: 'Attributes & Variants', icon: Tags },
      { to: '/admin/desk/products/bulk', label: 'Bulk Editor', icon: FileText },
      { to: '/admin/desk/products/import-export', label: 'Import / Export', icon: FileText },
      { to: '/admin/desk/products/feeds', label: 'Product Feeds', icon: Radio },
      { to: '/admin/bundles', label: 'Bundles & Kits', icon: Package },
      { to: '/admin/desk/products/digital', label: 'Digital Products', icon: FileText },
      { to: '/admin/desk/products/purchase-orders', label: 'Purchase Orders', icon: FileText },
      { to: '/admin/desk/products/approvals', label: 'Product Approvals', icon: ShieldCheck },
      { to: '/admin/desk/products/settings', label: 'Product Settings', icon: SettingsIcon },
    ],
  },
  {
    key: 'customers', label: 'Customers', icon: Users,
    match: ['/admin/customers', '/admin/loyalty'],
    children: [
      { to: '/admin/customers', label: 'All Customers', icon: Users },
      { to: '/admin/customers/groups', label: 'Customer Groups', icon: Users },
      { to: '/admin/customers/segments', label: 'Customer Segments', icon: Users },
      { to: '/admin/customers/vip', label: 'VIP Customers', icon: Sparkles },
      { to: '/admin/loyalty', label: 'Loyalty', icon: Sparkles },
      { to: '/admin/customers/messages', label: 'Customer Messages', icon: MessageSquare },
      { to: '/admin/reviews', label: 'Customer Reviews', icon: Star },
      { to: '/admin/customers/settings', label: 'Customer Settings', icon: SettingsIcon },
    ],
  },
  {
    key: 'storefront', label: 'Storefront', icon: Store,
    match: ['/admin/store', '/admin/theme', '/admin/cms', '/admin/content', '/admin/faq', '/admin/markets', '/admin/blog', '/admin/navigation', '/admin/media', '/admin/seo'],
    children: [
      { to: '/admin/store', label: 'Store Overview', icon: Globe },
      { to: '/admin/theme', label: 'Theme Studio', icon: LayoutTemplate },
      { to: '/admin/theme/library', label: 'Theme Library', icon: LayoutTemplate },
      { to: '/admin/theme', label: 'Current Theme', icon: LayoutTemplate },
      { to: '/admin/theme/drafts', label: 'Draft Themes', icon: LayoutTemplate },
      { to: '/admin/theme/styles', label: 'Global Styles', icon: LayoutTemplate },
      { to: '/admin/theme-sections', label: 'Sections', icon: LayoutTemplate },
      { to: '/admin/theme/blocks', label: 'Blocks', icon: LayoutTemplate },
      { to: '/admin/theme/templates', label: 'Templates', icon: LayoutTemplate },
      { to: '/admin/theme/app-blocks', label: 'App Blocks', icon: LayoutTemplate },
      { to: '/admin/theme/settings', label: 'Theme Settings', icon: SettingsIcon },
      { to: '/admin/theme/homepage', label: 'Homepage', icon: Home },
      { to: '/admin/theme/product-page', label: 'Product Page', icon: Package },
      { to: '/admin/theme/collection-page', label: 'Collection Page', icon: FolderOpen },
      { to: '/admin/settings/cart', label: 'Cart Page', icon: ShoppingBag },
      { to: '/admin/settings/checkout', label: 'Checkout Page', icon: CreditCard },
      { to: '/admin/cms', label: 'Pages', icon: FileText },
      { to: '/admin/blog', label: 'Blog', icon: FileText },
      { to: '/admin/faq', label: 'FAQ', icon: FileText },
      { to: '/admin/navigation', label: 'Navigation', icon: Menu },
      { to: '/admin/media', label: 'Media Library', icon: ImagePlus },
      { to: '/admin/content', label: 'Content', icon: ImagePlus },
      { to: '/admin/seo', label: 'SEO', icon: Search },
      { to: '/admin/cms/redirects', label: 'Old addresses', icon: Signpost },
      { to: '/admin/store/preview', label: 'Store Preview', icon: Globe },
      { to: '/admin/store/publish', label: 'Publish Changes', icon: Zap },
      { to: '/admin/markets', label: 'Markets', icon: Globe },
    ],
  },
  {
    key: 'marketing', label: 'Marketing', icon: Megaphone,
    match: ['/admin/promotions', '/admin/bundles', '/admin/flash-sales', '/admin/marketing', '/admin/email-campaigns', '/admin/banners', '/admin/sms'],
    children: [
      { to: '/admin/marketing', label: 'Marketing Overview', icon: Megaphone },
      { to: '/admin/promotions', label: 'Campaigns', icon: Megaphone },
      { to: '/admin/marketing/settings', label: 'Automations', icon: SettingsIcon },
      { to: '/admin/email-campaigns', label: 'Email Marketing', icon: Mail },
      { to: '/admin/sms', label: 'SMS Marketing', icon: Phone },
      { to: '/admin/abandoned-carts', label: 'Abandoned Cart', icon: PackageX },
      { to: '/admin/customers/segments', label: 'Customer Segments', icon: Users },
      { to: '/admin/banners', label: 'Banners', icon: ImagePlus },
      { to: '/admin/bundles', label: 'Bundles', icon: Package },
      { to: '/admin/flash-sales', label: 'Flash sales', icon: Zap },
      { to: '/admin/marketing/analytics', label: 'Performance', icon: BarChart3 },
      { to: '/admin/marketing/settings', label: 'Marketing Settings', icon: SettingsIcon },
    ],
  },
  {
    key: 'discounts', label: 'Discounts', icon: BadgePercent,
    match: ['/admin/discounts', '/admin/gift-cards'],
    children: [
      { to: '/admin/discounts', label: 'Discount Codes', icon: BadgePercent },
      { to: '/admin/discounts/automatic', label: 'Automatic Discounts', icon: BadgePercent },
      { to: '/admin/discounts/percent', label: 'Percentage Discounts', icon: BadgePercent },
      { to: '/admin/discounts/fixed', label: 'Fixed Amount Discounts', icon: BadgePercent },
      { to: '/admin/discounts/free-shipping', label: 'Free Shipping', icon: Truck },
      { to: '/admin/discounts/bogo', label: 'Buy X Get Y', icon: Gift },
      { to: '/admin/gift-cards', label: 'Gift Cards', icon: Gift },
      { to: '/admin/discounts/settings', label: 'Discount Settings', icon: SettingsIcon },
    ],
  },
  {
    key: 'analytics', label: 'Analytics', icon: BarChart3,
    match: ['/admin/analytics', '/admin/insights', '/admin/finance', '/admin/live', '/admin/growth', '/admin/search-analytics', '/admin/reports'],
    children: [
      { to: '/admin/analytics', label: 'Analytics Overview', icon: BarChart3 },
      { to: '/admin/reports/sales', label: 'Sales', icon: BarChart3 },
      { to: '/admin/reports/orders', label: 'Orders', icon: ShoppingBag },
      { to: '/admin/reports/products', label: 'Products', icon: Package },
      { to: '/admin/reports/customers', label: 'Customers', icon: Users },
      { to: '/admin/reports/inventory', label: 'Inventory', icon: Box },
      { to: '/admin/reports/marketing', label: 'Marketing', icon: Megaphone },
      { to: '/admin/reports/conversion', label: 'Conversion', icon: Activity },
      { to: '/admin/finance', label: 'Finance & P&L', icon: CreditCard },
      { to: '/admin/insights', label: 'Deep Insights', icon: Activity },
      { to: '/admin/search-analytics', label: 'Search Analytics', icon: Search },
      { to: '/admin/live', label: 'Live View', icon: Activity },
      { to: '/admin/growth', label: 'Growth', icon: Activity },
      { to: '/admin/reports', label: 'Reports', icon: FileText },
      { to: '/admin/reports/export', label: 'Export Reports', icon: FileText },
    ],
  },
  {
    key: 'channels', label: 'Sales Channels', icon: Radio,
    match: ['/admin/channels'],
    children: [
      { to: '/admin/store', label: 'Online Store', icon: Globe },
      { to: '/admin/channels/online/availability', label: 'Product Availability', icon: Package },
      { to: '/admin/channels/online/collections', label: 'Collection Availability', icon: FolderOpen },
      { to: '/admin/channels/online/settings', label: 'Channel Settings', icon: SettingsIcon },
      { to: '/admin/channels/mobile', label: 'Mobile Store', icon: Smartphone },
      { to: '/admin/channels/mobile/catalog', label: 'Mobile Catalog', icon: Smartphone },
      { to: '/admin/channels/mobile/home', label: 'Mobile Homepage', icon: Home },
      { to: '/admin/channels/mobile/settings', label: 'Mobile Settings', icon: SettingsIcon },
      { to: '/admin/channels/social', label: 'Social Commerce', icon: Megaphone },
      { to: '/admin/channels/social/catalog', label: 'Social Catalog', icon: Megaphone },
      { to: '/admin/channels/social/products', label: 'Social Products', icon: Package },
      { to: '/admin/channels/social/settings', label: 'Social Settings', icon: SettingsIcon },
      { to: '/admin/channels/marketplaces', label: 'Marketplaces', icon: Store },
      { to: '/admin/channels/marketplaces/catalog', label: 'Marketplace Catalog', icon: Store },
      { to: '/admin/channels/marketplaces/listings', label: 'Marketplace Listings', icon: Tags },
      { to: '/admin/channels/marketplaces/settings', label: 'Marketplace Settings', icon: SettingsIcon },
      { to: '/admin/channels/add', label: 'Add Channel', icon: Plus },
      { to: '/admin/channels/future/catalog', label: 'Channel Catalog', icon: Radio },
      { to: '/admin/channels/future/orders', label: 'Channel Orders', icon: ShoppingBag },
      { to: '/admin/channels/future/settings', label: 'Future Channel Settings', icon: SettingsIcon },
    ],
  },
  {
    key: 'apps', label: 'Apps & Integrations', icon: Zap,
    match: ['/admin/apps', '/admin/integrations'],
    children: [
      { to: '/admin/apps', label: 'Installed Apps', icon: Zap },
      { to: '/admin/apps/marketplace', label: 'App Marketplace', icon: Store },
      { to: '/admin/apps/payments', label: 'Payment Integrations', icon: CreditCard },
      { to: '/admin/apps/shipping', label: 'Shipping Integrations', icon: Truck },
      { to: '/admin/apps/marketing', label: 'Marketing Integrations', icon: Megaphone },
      { to: '/admin/apps/analytics', label: 'Analytics Integrations', icon: BarChart3 },
      { to: '/admin/apps/storefront', label: 'Storefront Integrations', icon: Globe },
      { to: '/admin/apps/import', label: 'Import Connections', icon: FileText },
      { to: '/admin/apps/api-keys', label: 'API Keys', icon: KeyRound },
      { to: '/admin/apps/webhooks', label: 'Webhooks', icon: Webhook },
      { to: '/admin/apps/logs', label: 'Integration Logs', icon: FileText },
    ],
  },
  {
    key: 'settings', label: 'Settings', icon: SettingsIcon,
    match: ['/admin/settings', '/admin/backup', '/admin/team', '/admin/billing'],
    children: [
      { to: '/admin/settings', label: 'Settings Hub', icon: SettingsIcon },
      { to: '/admin/settings/store', label: 'General / Store Details', icon: Store },
      { to: '/admin/settings/domain', label: 'Domain', icon: Globe },
      { to: '/admin/settings/currency', label: 'Currency', icon: CreditCard },
      { to: '/admin/settings/languages', label: 'Languages', icon: Globe },
      { to: '/admin/settings/checkout', label: 'Checkout', icon: CreditCard },
      { to: '/admin/settings/accounts', label: 'Customer Accounts', icon: Users },
      { to: '/admin/settings/email', label: 'Notifications', icon: Mail },
      { to: '/admin/settings/legal', label: 'Policies', icon: FileText },
      { to: '/admin/settings/privacy', label: 'Privacy', icon: ShieldCheck },
      { to: '/admin/settings/payments', label: 'Payments', icon: CreditCard },
      { to: '/admin/settings/payments/methods', label: 'Payment Methods', icon: CreditCard },
      { to: '/admin/settings/payments/providers', label: 'Payment Providers', icon: CreditCard },
      { to: '/admin/settings/payments/transactions', label: 'Transactions', icon: CreditCard },
      { to: '/admin/settings/payments/payouts', label: 'Payouts', icon: CreditCard },
      { to: '/admin/settings/payments/refunds', label: 'Refund Settings', icon: CreditCard },
      { to: '/admin/settings/payments/notifications', label: 'Payment Notifications', icon: Bell },
      { to: '/admin/settings/shipping', label: 'Shipping & Delivery', icon: Truck },
      { to: '/admin/settings/shipping/zones', label: 'Shipping Zones', icon: Truck },
      { to: '/admin/settings/shipping/rates', label: 'Shipping Rates', icon: Truck },
      { to: '/admin/settings/shipping/methods', label: 'Delivery Methods', icon: Truck },
      { to: '/admin/settings/shipping/providers', label: 'Shipping Providers', icon: Truck },
      { to: '/admin/settings/shipping/locations', label: 'Fulfillment Locations', icon: Building2 },
      { to: '/admin/settings/shipping/pickup', label: 'Pickup', icon: Store },
      { to: '/admin/settings/taxes', label: 'Taxes', icon: Calculator },
      { to: '/admin/settings/taxes/regions', label: 'Tax Regions', icon: Calculator },
      { to: '/admin/settings/taxes/rates', label: 'Tax Rates', icon: Calculator },
      { to: '/admin/settings/taxes/classes', label: 'Tax Classes', icon: Calculator },
      { to: '/admin/settings/taxes/exemptions', label: 'Tax Exemptions', icon: Calculator },
      { to: '/admin/markets/countries', label: 'Countries', icon: Globe },
      { to: '/admin/markets/currencies', label: 'Currencies', icon: CreditCard },
      { to: '/admin/markets/languages', label: 'Market Languages', icon: Globe },
      { to: '/admin/markets/pricing', label: 'Regional Pricing', icon: Tags },
      { to: '/admin/markets/catalogs', label: 'Regional Catalogs', icon: FolderOpen },
      { to: '/admin/markets/domains', label: 'Regional Domains', icon: Globe },
      { to: '/admin/markets/taxes', label: 'Regional Taxes', icon: Calculator },
      { to: '/admin/markets/shipping', label: 'Regional Shipping', icon: Truck },
      { to: '/admin/team', label: 'Team Members', icon: Users },
      { to: '/admin/team/roles', label: 'Roles', icon: ShieldCheck },
      { to: '/admin/team/permissions', label: 'Custom Permissions', icon: ShieldCheck },
      { to: '/admin/team/store-access', label: 'Store Access', icon: Store },
      { to: '/admin/team/product-access', label: 'Product Access', icon: Package },
      { to: '/admin/team/order-access', label: 'Order Access', icon: ShoppingBag },
      { to: '/admin/team/customer-access', label: 'Customer Access', icon: Users },
      { to: '/admin/team/finance-access', label: 'Finance Access', icon: CreditCard },
      { to: '/admin/team/activity', label: 'Login Activity', icon: Activity },
      { to: '/admin/billing', label: 'Current Plan', icon: CreditCard },
      { to: '/admin/billing/upgrade', label: 'Upgrade Plan', icon: Zap },
      { to: '/admin/billing/usage', label: 'Usage', icon: BarChart3 },
      { to: '/admin/billing/invoices', label: 'Invoices', icon: FileText },
      { to: '/admin/billing/payment-method', label: 'Billing Payment Method', icon: CreditCard },
      { to: '/admin/billing/seats', label: 'Team Seats', icon: Users },
      { to: '/admin/billing/stores', label: 'Connected Stores', icon: Store },
      { to: '/admin/billing/subscription', label: 'Subscription Settings', icon: SettingsIcon },
      { to: '/admin/settings/advanced', label: 'Advanced', icon: SettingsIcon },
      { to: '/admin/settings/api', label: 'API & Webhooks', icon: Webhook },
      { to: '/admin/settings/custom-data', label: 'Custom Data', icon: FileText },
      { to: '/admin/settings/metafields', label: 'Metafields', icon: Tags },
      { to: '/admin/settings/automations', label: 'Automations', icon: Zap },
      { to: '/admin/backup', label: 'Data Export / Backup', icon: FileText },
      { to: '/admin/settings/activity-logs', label: 'Activity Logs', icon: FileText },
      { to: '/admin/settings/error-logs', label: 'Error Logs', icon: FileText },
      { to: '/admin/settings/security', label: 'Security', icon: ShieldCheck },
      { to: '/admin/settings/developer', label: 'Developer Tools', icon: KeyRound },
      { to: '/admin/settings/cart', label: 'Shopping Bag', icon: ShoppingBag },
    ],
  },
];

export const FOOTER_LINKS = [
  { to: '/', label: 'View Store', icon: Globe, external: true },
  { to: '/admin/help', label: 'Help & Support', icon: LifeBuoy },
  { to: '/admin/docs', label: 'Documentation', icon: BookOpen },
  { to: '/admin/shortcuts', label: 'Keyboard Shortcuts', icon: Keyboard },
  { to: '/admin/profile', label: 'Admin Profile', icon: Users },
];
